name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: |
          ssh -v -i ~/.ssh/id_rsa ${{ secrets.EC2_HOST }} "echo '✅ Connected to EC2!'"

      - name: Deploy Code to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/jira_tracker  # Change to your actual path
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF
